apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-app
        image: gcr.io/PROJECT_ID/web-app:COMMIT_SHA
        ports:
        - containerPort: 8080
