name: GCP Infrastructure Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  CLUSTER_NAME: task9-gke-cluster
  RUNNER_VM_NAME: github-runner-vm

jobs:
  create-runner:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup GCP
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Create Runner VM
      run: |
        gcloud compute instances create ${{ env.RUNNER_VM_NAME }} \
          --project=${{ env.PROJECT_ID }} \
          --zone=${{ env.REGION }}-a \
          --machine-type=e2-medium \
          --image-family=ubuntu-2204-lts \
          --image-project=ubuntu-os-cloud \
          --boot-disk-size=20GB \
          --tags=github-runner \
          --scopes=cloud-platform \
          --metadata-from-file=startup-script=.github/scripts/gcp-runner-setup.sh

    - name: Wait for VM initialization
      run: sleep 120

  terraform-apply:
    needs: create-runner
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="project_id=${{ env.PROJECT_ID }}"
      working-directory: ./terraform

  deploy-app:
    needs: terraform-apply
    runs-on: self-hosted
    steps:
    - name: Setup GCP
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Build and Push Container
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/task9-app:${{ github.sha }} ./app
        docker push gcr.io/${{ env.PROJECT_ID }}/task9-app:${{ github.sha }}

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
          --region ${{ env.REGION }} \
          --project ${{ env.PROJECT_ID }}
        
        sed -i "s|IMAGE_PLACEHOLDER|gcr.io/${{ env.PROJECT_ID }}/task9-app:${{ github.sha }}|g" ./app/manifests/deployment.yaml
        kubectl apply -f ./app/manifests/